# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-21 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelsey_group', to='otree.Session')),
            ],
            options={
                'db_table': 'kelsey_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('consent', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('treatment', otree.db.models.StringField(max_length=10000, null=True)),
                ('investment_payoff', otree.db.models.IntegerField(null=True)),
                ('low_payoff', otree.db.models.IntegerField(null=True)),
                ('high_payoff', otree.db.models.IntegerField(null=True)),
                ('first_decision', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('second_decision', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Do you want to pay the final\n        investment cost of $15 to\n         release this payoff?')),
                ('temporary_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_to_pay_part1', otree.db.models.IntegerField(null=True)),
                ('round_to_pay_part2', otree.db.models.IntegerField(null=True)),
                ('q3_T0', otree.db.models.StringField(choices=[('16', '16'), ('12', '12')], max_length=10000, null=True, verbose_name='What are your earnings for the round in the previous example if the payoff is 40 points and you chose to pay the initial investment cost (9 points)?')),
                ('q2_T0', otree.db.models.StringField(choices=[('-9', '-9'), ('-16', '-16')], max_length=10000, null=True, verbose_name='What are your earnings for the round in the previous example if the payoff is 8 points and you choose to pay the initial investment cost (9 points)?')),
                ('q1_T0', otree.db.models.StringField(choices=[('-6', '-6'), ('0', '0')], max_length=10000, null=True, verbose_name='What are your earnings for the round in the previous example if you choose not to pay the initial investment cost (9 points)?')),
                ('q1_T1', otree.db.models.StringField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=10000, null=True, verbose_name='Would you be able to release the payoff by paying the final investment cost if you do not pay the initial investment cost?')),
                ('q2_T1', otree.db.models.StringField(choices=[('6', '6'), ('16', '16')], max_length=10000, null=True, verbose_name='What would have been your earnings for the round in the previous example if the payoff were 40 points, and you had chosen to pay both the initial investment cost (9 points) and the final investment cost (15 points)?')),
                ('q3_T1', otree.db.models.StringField(choices=[('6', '6'), ('-16', '-16')], max_length=10000, null=True, verbose_name='What would have been your earnings for the round in the previous example if the payoff were 8 points, and you had chosen to pay both the initial investment cost (9 points) and the final investment cost (15 points)?')),
                ('q4_T1', otree.db.models.StringField(choices=[('12', '12'), ('-9', '-9')], max_length=10000, null=True, verbose_name='What would have been your earnings in this round if you chose to pay only the initial investment cost (9 points), but not the final investment cost?')),
                ('q1_T2', otree.db.models.StringField(choices=[('16', '16'), ('6', '6')], max_length=10000, null=True, verbose_name='What are your earnings for the round in the previous example if the payoff is 40 points and you chose to pay the initial investment cost (9 points) and the final investment cost (15 points)?')),
                ('q2_T2', otree.db.models.StringField(choices=[('-16', '-16'), ('-5', '-5')], max_length=10000, null=True, verbose_name='What are your earnings for the round in the previous example if the payoff is 8 points and you chose to pay the initial investment cost (9 points) and the final investment cost (15 points)?')),
                ('q3_T2', otree.db.models.StringField(choices=[('-6', '-6'), ('0', '0')], max_length=10000, null=True, verbose_name='What are your earnings for the round in the previous example if you choose not to pay the initial investment cost (9 points) and the final investment cost (15 points)?')),
                ('gender', otree.db.models.StringField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10000, null=True, verbose_name='Gender')),
                ('nationality', otree.db.models.StringField(choices=[('US', 'US'), ('Other', 'Other')], max_length=10000, null=True, verbose_name='Nationality')),
                ('nationality_other', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='')),
                ('race_ethnicity', otree.db.models.StringField(choices=[('African American/African/Black/Caribbean', 'African American/African/Black/Caribbean'), ('Asian/Pacific Islander', 'Asian/Pacific Islander'), ('Caucasian', 'Caucasian'), ('Hispanic/Latino', 'Hispanic/Latino'), ('Native American', 'Native American'), ('Other', 'Other'), ('Prefer not to answer ', 'Prefer not to answer ')], max_length=10000, null=True, verbose_name='Race/Ethnicity')),
                ('race_ethnicity_other', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='')),
                ('major', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Major')),
                ('year_in_college', otree.db.models.StringField(blank=True, choices=[('Freshman/First-Year ', 'Freshman/First-Year '), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Graduate Student', 'Graduate Student'), ('Other', 'Other')], max_length=10000, null=True, verbose_name='If you are currently in school, what year are you in?')),
                ('year_in_college_other', otree.db.models.StringField(max_length=10000, null=True, verbose_name='')),
                ('stock_market_experience', otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True, verbose_name='Do you have any experience with the stock market?')),
                ('stock_market_explain', otree.db.models.StringField(max_length=10000, null=True, verbose_name='')),
                ('instructions', otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True, verbose_name='Were the instructions clear?')),
                ('recommendations', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Do you have any recommendations for improvements?')),
                ('random_contract', otree.db.models.StringField(choices=[('Very Confident', 'Very Confident'), ('Confident', 'Confident'), ('Somewhat Unconfident', 'Somewhat Unconfident'), ('Unconfident', 'Unconfident')], max_length=10000, null=True, verbose_name='How confident were you that the experimenters truly randomized the payoff of each contract based on the stated probabilities?')),
                ('random_round', otree.db.models.StringField(choices=[('Very Confident', 'Very Confident'), ('Confident', 'Confident'), ('Somewhat Unconfident', 'Somewhat Unconfident'), ('Unconfident', 'Unconfident')], max_length=10000, null=True, verbose_name='How confident were you that the experimenters truly chose the rounds for payments randomly?')),
                ('easiest', otree.db.models.StringField(choices=[('Part 1', 'Part 1'), ('Part 2', 'Part 2')], max_length=10000, null=True, verbose_name='Which Part of the experiment did you find was easiest to think through?')),
                ('end_beginning', otree.db.models.StringField(choices=[('Beginning', 'Beginning'), ('End', 'End')], max_length=10000, null=True, verbose_name='Do you think you made better decisions at the end of each Part or at the beginning of each Part?')),
                ('pleasant', otree.db.models.StringField(choices=[('Extremely Pleasant', 'Extremely Pleasant'), ('Pleasant', 'Pleasant'), ('Somewhat Pleasant', 'Somewhat Pleasant'), ('Neither', 'Neither'), ('Somewhat Unpleasant', 'Somewhat Unpleasant'), ('Unpleasant', 'Unpleasant'), ('Extremely Unpleasant', 'Extremely Unpleasant')], max_length=10000, null=True, verbose_name='Would you say that you found being in this study a pleasant or unpleasant experience?')),
                ('thinking', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Please try to describe what you were thinking when you were making decisions \n        during the study.  What factors entered your decisions? And why did you make the choices you did?')),
                ('stage3decision', otree.db.models.StringField(max_length=10000, null=True)),
                ('stage3_chosen_lottery', otree.db.models.IntegerField(null=True)),
                ('stage3_picked_number', otree.db.models.IntegerField(null=True)),
                ('stage3_payoff', otree.db.models.CurrencyField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kelsey.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelsey_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelsey_player', to='otree.Session')),
            ],
            options={
                'db_table': 'kelsey_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kelsey_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'kelsey_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kelsey.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kelsey.Subsession'),
        ),
    ]
