# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-02 15:30
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('kelsey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='temporary_payoff',
        ),
        migrations.AddField(
            model_name='player',
            name='game_payoff',
            field=otree.db.models.CurrencyField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='general_comments',
            field=otree.db.models.LongStringField(blank=True, null=True, verbose_name='Please share with us any comments or questions you have in a course of the study'),
        ),
        migrations.AddField(
            model_name='player',
            name='vars_dump',
            field=otree.db.models.LongStringField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='q1_T0',
            field=otree.db.models.StringField(choices=[('-25', '-25'), ('0', '0')], max_length=10000, null=True, verbose_name='What are your earnings for the round in the previous example if you choose not to pay the initial investment cost (25 points)?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q1_T2',
            field=otree.db.models.StringField(choices=[('20', '20'), ('10', '10')], max_length=10000, null=True, verbose_name='What are your earnings for the round in the previous example if the payoff is 90 points and you chose to pay the initial investment cost (25 points) and the final investment cost (45 points)?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q2_T0',
            field=otree.db.models.StringField(choices=[('0', '0'), ('-25', '-25')], max_length=10000, null=True, verbose_name='What are your earnings for the round in the previous example if the payoff is 0 points and you choose to pay the initial investment cost (25 points)?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q2_T1',
            field=otree.db.models.StringField(choices=[('45', '45'), ('20', '20')], max_length=10000, null=True, verbose_name='What would have been your earnings for the round in the previous example if the payoff were 90 points, and you had chosen to pay both the initial investment cost (25 points) and the final investment cost (45 points)?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q2_T2',
            field=otree.db.models.StringField(choices=[('-50', '-50'), ('-70', '-70')], max_length=10000, null=True, verbose_name='What are your earnings for the round in the previous example if the payoff is 0 points and you chose to pay the initial investment cost (25 points) and the final investment cost (45 points)?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q3_T0',
            field=otree.db.models.StringField(choices=[('20', '20'), ('10', '10')], max_length=10000, null=True, verbose_name='What are your earnings for the round in the previous example if the payoff is 90 points and you chose to pay the initial investment cost (25 points)?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q3_T1',
            field=otree.db.models.StringField(choices=[('-70', '-70'), ('-40', '-40')], max_length=10000, null=True, verbose_name='What would have been your earnings for the round in the previous example if the payoff were 0 points, and you had chosen to pay both the initial investment cost (25 points) and the final investment cost (45 points)?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q3_T2',
            field=otree.db.models.StringField(choices=[('0', '0'), ('-20', '-20')], max_length=10000, null=True, verbose_name='What are your earnings for the round in the previous example if you choose not to pay the initial investment cost (25 points) and the final investment cost (45 points)?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q4_T1',
            field=otree.db.models.StringField(choices=[('-25', '-25'), ('0', '0')], max_length=10000, null=True, verbose_name='What would have been your earnings in this round if you chose to pay only the initial investment cost (25 points), but not the final investment cost?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='second_decision',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Do you want to pay the final\n        investment cost of 45 points to\n         release this payoff?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='thinking',
            field=otree.db.models.LongStringField(blank=True, null=True, verbose_name='Please try to describe what you were thinking when you were making decisions \n        during the study.  What factors entered your decisions? And why did you make the choices you did?'),
        ),
    ]
